### ISSUE TITLE
PR Release

### ISSUE THREAD

**Issue by rileyhgrant** [broadinstitute/genetic-prevalence-estimator#232]
GeniE is already public and has users, there is currently PR planned to make this app more known to users on Wednesday, May 29th.

This is issue serves as a punchlist of all the things that need to be accomplished ahead of May 29th.

GeniE is having PR discussing in on **Tuesday Jun 04, 2024**

---

#### Large features
- [x] #220 | Integrate gnomAD v4.1
- [x] #98 | Allow adding Structural Variants
- [ ]  | Add Analytics to track stats
- [x] #196 | Add Dashboard
  - [x] email hover overs -- truncate at a certain number of characters and add ...
  - [x] use OrphaNet prevalences
  - [x] standardize calculation format
  - [x] add inheritance types
  - [x] change backend to accept changes
  - [x] #233 
  - [x] Make dashboard publicly available, not just to Staff. Replace "public lists" with "Dashboard"
  - [x] #236 | Add pagination and searchability to DashboardList page
  - [x] Reformat OrphaNet urls to link to the Gene
  - [x] Add add'l tests
- [x] #212 | Populate dashboard with pre-calculated lists, provide file for download
- [x] #231 | Add flags to dashboard calculation logic
- [ ] #211 | ClinVar auto-monthly
- [x] | v2 SV support
- [x] | edit v2 pipeline, reload v2 data with `homozygote_count`
- [ ] | add tests to validate the current variant adding behavior (if add malformed, 400, if add SV on v2, malformed, etc)
- [x] | add proper structural variant type in `../types.ts`

#### Smaller features
- [x] #172 | Add additional genetic prevalence formula
- [x] #161 | Add flags (TODO: split this into 3 tickets, one per flag)
  - [x] #219 | `Low_AN`
  - [x] #171 | `High_AF`
  - [x] #237 | `# Homozygotes`
- [x] #213 | Optionally remove homozygotes from calcs (dashboard too?)
- [x] #173 | Remove HC LoF that have B/LB in ClinVar, also high revel scores but B/LB
- [x] | Make `AF` column fit in default view
- [x] | Allow naming of supporting documents (also maybe more than 1 supporting doc?)
- [x] | Allow adding of SVs in v4 custom lists
- [ ] | Hide submitting for representative to only if its already public? or if its representative, think about this, make more intuitive

#### Copy edits
- [x] | edit wording of homozygote tooltip: "<#> homozygous individual(s) in gnomAD"
- [x] | edit wording of homozygote toggle: "include gnomAD homozygotes in calculations"
- [x] | edit wording of Dashboard Lists -> Dashboard, both in url and header of page
- [x] | edit wording of submitting for representivity -> apply to be included on dashboard
- [x] | edit wording for "not representative" to "This variant list is not currently represented on the GeniE Dashboard"
- [x] Header "representivity" should change, maybe just "Dashboard"
- [x] #166 | Update website text
- [x] #162 | Add hover over text
- [x] #230 | Update help text

#### Bugfixes
- [ ] #228 | Don't include conflicting ClinVar where non are path/likely path
- [ ] #227 | Check if component hooks get called on page scroll events

#### Time Sensitive
- [x] Generate full dashboard_models / dashboard_downloads files
- [x] https://github.com/broadinstitute/gnomad-blog/pull/157 | Stage blog - release on day
